/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as TrackingRouteImport } from './routes/tracking'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ProductProductIdRouteImport } from './routes/product.$productId'
import { Route as ApiProductsRouteImport } from './routes/api.products'
import { Route as ApiOrdersRouteImport } from './routes/api.orders'
import { Route as ApiNewsletterRouteImport } from './routes/api.newsletter'
import { Route as ApiDashboardRouteImport } from './routes/api.dashboard'
import { Route as ApiContactRouteImport } from './routes/api.contact'
import { Route as ApiBrandRouteImport } from './routes/api.brand'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminProductsRouteImport } from './routes/admin.products'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminCustomersRouteImport } from './routes/admin.customers'
import { Route as ApiTrackingIdRouteImport } from './routes/api.tracking.$id'
import { Route as ApiProductsIdRouteImport } from './routes/api.products.$id'
import { Route as ApiOrdersIdRouteImport } from './routes/api.orders.$id'
import { Route as ApiAuthSignupRouteImport } from './routes/api.auth.signup'
import { Route as ApiAuthLoginRouteImport } from './routes/api.auth.login'

const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackingRoute = TrackingRouteImport.update({
  id: '/tracking',
  path: '/tracking',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ProductProductIdRoute = ProductProductIdRouteImport.update({
  id: '/product/$productId',
  path: '/product/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProductsRoute = ApiProductsRouteImport.update({
  id: '/api/products',
  path: '/api/products',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOrdersRoute = ApiOrdersRouteImport.update({
  id: '/api/orders',
  path: '/api/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNewsletterRoute = ApiNewsletterRouteImport.update({
  id: '/api/newsletter',
  path: '/api/newsletter',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDashboardRoute = ApiDashboardRouteImport.update({
  id: '/api/dashboard',
  path: '/api/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiContactRoute = ApiContactRouteImport.update({
  id: '/api/contact',
  path: '/api/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBrandRoute = ApiBrandRouteImport.update({
  id: '/api/brand',
  path: '/api/brand',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AdminRoute,
} as any)
const ApiTrackingIdRoute = ApiTrackingIdRouteImport.update({
  id: '/api/tracking/$id',
  path: '/api/tracking/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProductsIdRoute = ApiProductsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiProductsRoute,
} as any)
const ApiOrdersIdRoute = ApiOrdersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiOrdersRoute,
} as any)
const ApiAuthSignupRoute = ApiAuthSignupRouteImport.update({
  id: '/api/auth/signup',
  path: '/api/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLoginRoute = ApiAuthLoginRouteImport.update({
  id: '/api/auth/login',
  path: '/api/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/shop': typeof ShopRoute
  '/signup': typeof SignupRoute
  '/tracking': typeof TrackingRoute
  '/wishlist': typeof WishlistRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/api/brand': typeof ApiBrandRoute
  '/api/contact': typeof ApiContactRoute
  '/api/dashboard': typeof ApiDashboardRoute
  '/api/newsletter': typeof ApiNewsletterRoute
  '/api/orders': typeof ApiOrdersRouteWithChildren
  '/api/products': typeof ApiProductsRouteWithChildren
  '/product/$productId': typeof ProductProductIdRoute
  '/admin/': typeof AdminIndexRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/signup': typeof ApiAuthSignupRoute
  '/api/orders/$id': typeof ApiOrdersIdRoute
  '/api/products/$id': typeof ApiProductsIdRoute
  '/api/tracking/$id': typeof ApiTrackingIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/shop': typeof ShopRoute
  '/signup': typeof SignupRoute
  '/tracking': typeof TrackingRoute
  '/wishlist': typeof WishlistRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/api/brand': typeof ApiBrandRoute
  '/api/contact': typeof ApiContactRoute
  '/api/dashboard': typeof ApiDashboardRoute
  '/api/newsletter': typeof ApiNewsletterRoute
  '/api/orders': typeof ApiOrdersRouteWithChildren
  '/api/products': typeof ApiProductsRouteWithChildren
  '/product/$productId': typeof ProductProductIdRoute
  '/admin': typeof AdminIndexRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/signup': typeof ApiAuthSignupRoute
  '/api/orders/$id': typeof ApiOrdersIdRoute
  '/api/products/$id': typeof ApiProductsIdRoute
  '/api/tracking/$id': typeof ApiTrackingIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/shop': typeof ShopRoute
  '/signup': typeof SignupRoute
  '/tracking': typeof TrackingRoute
  '/wishlist': typeof WishlistRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/api/brand': typeof ApiBrandRoute
  '/api/contact': typeof ApiContactRoute
  '/api/dashboard': typeof ApiDashboardRoute
  '/api/newsletter': typeof ApiNewsletterRoute
  '/api/orders': typeof ApiOrdersRouteWithChildren
  '/api/products': typeof ApiProductsRouteWithChildren
  '/product/$productId': typeof ProductProductIdRoute
  '/admin/': typeof AdminIndexRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/signup': typeof ApiAuthSignupRoute
  '/api/orders/$id': typeof ApiOrdersIdRoute
  '/api/products/$id': typeof ApiProductsIdRoute
  '/api/tracking/$id': typeof ApiTrackingIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/checkout'
    | '/contact'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/shop'
    | '/signup'
    | '/tracking'
    | '/wishlist'
    | '/admin/customers'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/settings'
    | '/api/brand'
    | '/api/contact'
    | '/api/dashboard'
    | '/api/newsletter'
    | '/api/orders'
    | '/api/products'
    | '/product/$productId'
    | '/admin/'
    | '/api/auth/login'
    | '/api/auth/signup'
    | '/api/orders/$id'
    | '/api/products/$id'
    | '/api/tracking/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/checkout'
    | '/contact'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/shop'
    | '/signup'
    | '/tracking'
    | '/wishlist'
    | '/admin/customers'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/settings'
    | '/api/brand'
    | '/api/contact'
    | '/api/dashboard'
    | '/api/newsletter'
    | '/api/orders'
    | '/api/products'
    | '/product/$productId'
    | '/admin'
    | '/api/auth/login'
    | '/api/auth/signup'
    | '/api/orders/$id'
    | '/api/products/$id'
    | '/api/tracking/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/checkout'
    | '/contact'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/shop'
    | '/signup'
    | '/tracking'
    | '/wishlist'
    | '/admin/customers'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/settings'
    | '/api/brand'
    | '/api/contact'
    | '/api/dashboard'
    | '/api/newsletter'
    | '/api/orders'
    | '/api/products'
    | '/product/$productId'
    | '/admin/'
    | '/api/auth/login'
    | '/api/auth/signup'
    | '/api/orders/$id'
    | '/api/products/$id'
    | '/api/tracking/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  CheckoutRoute: typeof CheckoutRoute
  ContactRoute: typeof ContactRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ShopRoute: typeof ShopRoute
  SignupRoute: typeof SignupRoute
  TrackingRoute: typeof TrackingRoute
  WishlistRoute: typeof WishlistRoute
  ApiBrandRoute: typeof ApiBrandRoute
  ApiContactRoute: typeof ApiContactRoute
  ApiDashboardRoute: typeof ApiDashboardRoute
  ApiNewsletterRoute: typeof ApiNewsletterRoute
  ApiOrdersRoute: typeof ApiOrdersRouteWithChildren
  ApiProductsRoute: typeof ApiProductsRouteWithChildren
  ProductProductIdRoute: typeof ProductProductIdRoute
  ApiAuthLoginRoute: typeof ApiAuthLoginRoute
  ApiAuthSignupRoute: typeof ApiAuthSignupRoute
  ApiTrackingIdRoute: typeof ApiTrackingIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tracking': {
      id: '/tracking'
      path: '/tracking'
      fullPath: '/tracking'
      preLoaderRoute: typeof TrackingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/product/$productId': {
      id: '/product/$productId'
      path: '/product/$productId'
      fullPath: '/product/$productId'
      preLoaderRoute: typeof ProductProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/products': {
      id: '/api/products'
      path: '/api/products'
      fullPath: '/api/products'
      preLoaderRoute: typeof ApiProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/orders': {
      id: '/api/orders'
      path: '/api/orders'
      fullPath: '/api/orders'
      preLoaderRoute: typeof ApiOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/newsletter': {
      id: '/api/newsletter'
      path: '/api/newsletter'
      fullPath: '/api/newsletter'
      preLoaderRoute: typeof ApiNewsletterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dashboard': {
      id: '/api/dashboard'
      path: '/api/dashboard'
      fullPath: '/api/dashboard'
      preLoaderRoute: typeof ApiDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/contact': {
      id: '/api/contact'
      path: '/api/contact'
      fullPath: '/api/contact'
      preLoaderRoute: typeof ApiContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/brand': {
      id: '/api/brand'
      path: '/api/brand'
      fullPath: '/api/brand'
      preLoaderRoute: typeof ApiBrandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/customers': {
      id: '/admin/customers'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/tracking/$id': {
      id: '/api/tracking/$id'
      path: '/api/tracking/$id'
      fullPath: '/api/tracking/$id'
      preLoaderRoute: typeof ApiTrackingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/products/$id': {
      id: '/api/products/$id'
      path: '/$id'
      fullPath: '/api/products/$id'
      preLoaderRoute: typeof ApiProductsIdRouteImport
      parentRoute: typeof ApiProductsRoute
    }
    '/api/orders/$id': {
      id: '/api/orders/$id'
      path: '/$id'
      fullPath: '/api/orders/$id'
      preLoaderRoute: typeof ApiOrdersIdRouteImport
      parentRoute: typeof ApiOrdersRoute
    }
    '/api/auth/signup': {
      id: '/api/auth/signup'
      path: '/api/auth/signup'
      fullPath: '/api/auth/signup'
      preLoaderRoute: typeof ApiAuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/login': {
      id: '/api/auth/login'
      path: '/api/auth/login'
      fullPath: '/api/auth/login'
      preLoaderRoute: typeof ApiAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminCustomersRoute: typeof AdminCustomersRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCustomersRoute: AdminCustomersRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ApiOrdersRouteChildren {
  ApiOrdersIdRoute: typeof ApiOrdersIdRoute
}

const ApiOrdersRouteChildren: ApiOrdersRouteChildren = {
  ApiOrdersIdRoute: ApiOrdersIdRoute,
}

const ApiOrdersRouteWithChildren = ApiOrdersRoute._addFileChildren(
  ApiOrdersRouteChildren,
)

interface ApiProductsRouteChildren {
  ApiProductsIdRoute: typeof ApiProductsIdRoute
}

const ApiProductsRouteChildren: ApiProductsRouteChildren = {
  ApiProductsIdRoute: ApiProductsIdRoute,
}

const ApiProductsRouteWithChildren = ApiProductsRoute._addFileChildren(
  ApiProductsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  CheckoutRoute: CheckoutRoute,
  ContactRoute: ContactRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ShopRoute: ShopRoute,
  SignupRoute: SignupRoute,
  TrackingRoute: TrackingRoute,
  WishlistRoute: WishlistRoute,
  ApiBrandRoute: ApiBrandRoute,
  ApiContactRoute: ApiContactRoute,
  ApiDashboardRoute: ApiDashboardRoute,
  ApiNewsletterRoute: ApiNewsletterRoute,
  ApiOrdersRoute: ApiOrdersRouteWithChildren,
  ApiProductsRoute: ApiProductsRouteWithChildren,
  ProductProductIdRoute: ProductProductIdRoute,
  ApiAuthLoginRoute: ApiAuthLoginRoute,
  ApiAuthSignupRoute: ApiAuthSignupRoute,
  ApiTrackingIdRoute: ApiTrackingIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
